name: ML Pipeline CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install libraries
      run: |
        pip install pandas numpy scikit-learn

    - name: Dummy Check
      run: echo "Pipeline executed successfully"

    - name: Accuracy Check
      run: |
        python - <<EOF
        accuracy = 0.80
        if accuracy < 0.75:
            raise Exception("Accuracy below threshold")
        EOF
